### ISSUE TITLE
Inconsistent licenses

### ISSUE THREAD

**Issue by localheinz** [fabwu/dddinaction#2]
When looking at individual branches, I noticed they all have different licenses:

### `module-2`

https://github.com/fabwu/dddinaction/blob/ad91f5408250cf9f04155c76cfad5e7e1c2b489b/composer.json#L3

❗️ Also note that running 

```
$ composer validate
```

on `module-2` yields

```
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
License "GPL-3.0" is a deprecated SPDX license identifier, use "GPL-3.0-only" or "GPL-3.0-or-later" instead
```

### `module-3`

https://github.com/fabwu/dddinaction/blob/a553dceea58bf6a86322d9b8ce87449f4db7d63b/composer.json#L3

### `module-5`

https://github.com/fabwu/dddinaction/blob/c25304d3340804b9d38d51a6041893313375a1ca/composer.json#L3

### `module-6`

https://github.com/fabwu/dddinaction/blob/dcb0edbfa25366750cc7702cdeafab0ca30afbcb/composer.json#L3

### `module-7`

https://github.com/fabwu/dddinaction/blob/cbd423e099f284f2016ed253a7a59752b1d02d77/composer.json#L3

What do you think about using consistent licenses across all branches?

**Comment by fabwu** [comment]
Thanks for pointing that out! I switched to MIT and made the license consistent over all branches.
